### ISSUE TITLE
Allow multiple car registration numbers per user

### ISSUE THREAD

**Issue by devilmaycare** [paulbulman/ParkingRota#5]
Functionality to allow a user to have more than 1 car registration related to their user account?

**Comment by paulbulman** [comment]
Should be done, a mere ten-and-a-half months later...

It's not as neat as it might be from a data normalisation point of view, in that it's just an extra column on the users table - rather than e.g. a separate registration numbers table with a FK to the users table, which is probably the more theoretically 'correct' solution. That means that (a) everyone has it whether they have a second car or not, and (b) there's no way of adding a third value, which is technically possible - however it is a much simpler implementation. Hopefully nobody drives more than two cars in on a regular basis!
